version: '3'

services:
  django:
    build:
      context: .
      dockerfile: dockerfiles/django
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - DATABASE_URL
    volumes:
      - ./static_files:/code/static_files
    tty: true
    stdin_open: true

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=simple_todo
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

